name: simple multijob
on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "I am dragon.. roar" >> dragon.txt
        
        - name: upload dragon artifacts
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: path/to/artifact/world.txt # check github marketplace actions
          
    test_job:
        # we need to using upload and download artifacts to use the file from previous jobs because both are running in different machine

        needs: build_job #jobs must complete before this and run in sequence
        runs-on: ubuntu-latest
        steps:
        - name: download dragon artifacts
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file
        - name: test files exists
          run : grep -i "dragon" dragon.txt

    deploy_job:
        needs: test_job #[build_job,test_job]
        runs-on: ubuntu-latest
        steps:
        - name: download dragon artifacts
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file
        - name: Read File
          run: cat dragon.txt
        
        - name: deploy
          run : echo deploying...

